// Generated by CoffeeScript 1.9.1
var iconv, misc;

misc = require('../lib/misc');

iconv = require('iconv-lite');

module.exports = {
  name: 'bash.im',
  pattern: /!(баш|bash)\b[\s]*(\d+)?/,
  onMsg: function(msg, safe) {
    var id, res;
    id = msg.match[2];
    if (id == null) {
      res = misc.getAsBrowser("http://bash.im/forweb/?u").then(function(page) {
        var text;
        id = page.match(/bash.im\/quote\/(\d+)/)[1];
        text = page.match(/0;">([^]+?)<\' \+ \'\/div>/)[1];
        return [id, text.replace(/<' \+ 'br>/g, '\n').replace(/<' \+ 'br \/>/g, '\n')];
      });
    } else {
      res = misc.getAsBrowser("http://bash.im/quote/" + id, {
        encoding: null
      }).then(function(page) {
        var text;
        page = iconv.decode(page, 'win1251');
        text = page.match(/<div class="text">([^]+?)<\/div>/)[1];
        return [id, text.replace(/<br \/>/g, '\n').replace(/<br>/g, '\n')];
      });
    }
    return safe(res).then(function(arg) {
      var id, text;
      id = arg[0], text = arg[1];
      text = ("Цитата №" + id + "\n\n") + misc.entities.decode(text);
      return msg.send(text);
    });
  },
  onError: function(msg) {
    return msg.send('Баш уже не тот...');
  }
};
