// Generated by CoffeeScript 1.9.1
var HIKKA, MAX_PERIOD, SMALL_PERIOD, addMoment, bhToString, calculateBhLevel, logger, misc, newStats, randomHikka, smiles;

logger = require('winston');

misc = require('../lib/misc');

HIKKA = ['хикка', 'омега', 'корзинка', 'сыч'];

MAX_PERIOD = 24 * 3600 * 1000;

SMALL_PERIOD = 5 * 60 * 1000;

smiles = {
  sunglasses: String.fromCodePoint(0x1F60E),
  unamused: String.fromCodePoint(0x1F612),
  angry: String.fromCodePoint(0x1F620),
  rage: String.fromCodePoint(0x1F621),
  tengu: String.fromCodePoint(0x1F47A),
  boom: String.fromCodePoint(0x1F4A5)
};

randomHikka = function() {
  return misc.randomChoice(HIKKA);
};

newStats = function(userId) {
  return {
    id: userId,
    tyan: false,
    moments: [],
    status: randomHikka()
  };
};

addMoment = function(stats, now) {
  var m;
  stats.moments = (function() {
    var i, len, ref, results;
    ref = stats.moments;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      m = ref[i];
      if (now - m < MAX_PERIOD) {
        results.push(m);
      }
    }
    return results;
  })();
  return stats.moments.push(now);
};

calculateBhLevel = function(moments, now) {
  var i, len, m, peaks, prev;
  prev = 0;
  peaks = [];
  for (i = 0, len = moments.length; i < len; i++) {
    m = moments[i];
    if (m - prev > SMALL_PERIOD) {
      peaks.push(1);
    } else {
      peaks[peaks.length - 1] += 1;
    }
    prev = m;
  }
  logger.debug(JSON.stringify(peaks));
  if (peaks.length === 0) {
    return 0;
  } else {
    if (now - prev > SMALL_PERIOD) {
      return peaks.length;
    } else {
      return peaks.length - 1 + peaks[peaks.length - 1];
    }
  }
};

bhToString = function(bh) {
  switch (Math.ceil(bh / 2)) {
    case 0:
      return {
        icon: smiles.sunglasses,
        text: misc.randomChoice(['спокойствие', 'нирвана', 'будда', 'нулевой'])
      };
    case 1:
      return {
        icon: smiles.unamused,
        text: misc.randomChoice(['покалывание', 'легкий', 'недоволен', 'незначительный'])
      };
    case 2:
      return {
        icon: smiles.angry,
        text: misc.randomChoice(['печёт!', 'раскаляется', 'нешуточный', 'дымится'])
      };
    case 3:
      return {
        icon: smiles.rage,
        text: misc.randomChoice(['адский!', 'страшный!', 'красная тревога!', 'термоядерный!', 'стул плавится!'])
      };
    case 4:
      return {
        icon: smiles.tengu,
        text: misc.randomChoice(['Первая Космическая!', 'Сатанинский!', 'Титанический!', 'Убить Всех Человеков'])
      };
    default:
      return {
        icon: smiles.boom,
        text: 'FFFFUUUUUU!!! ' + smiles.rage + smiles.rage + smiles.rage
      };
  }
};

module.exports = {
  name: 'Bugurt',
  pattern: /!(bh|статус|тян|бугурт|багор|багет|бомбит|багратион|бамболейло|батруха|баттхерт|бантустан|бранденбург|будапешт|будда|баргест|блюменталь|бакенбард|боль|бубалех|печет|печёт|припекло|пиздец|бля|сука|спок)(.*)/,
  init: function() {
    var ref;
    return this.stats = (ref = misc.loadJson('bh_stats')) != null ? ref : {};
  },
  onMsg: function(msg) {
    var base, bhLevel, now, ref, stats, userId;
    if (msg.match[1].toLowerCase() === 'bh') {
      return this.handleAdmin(msg);
    }
    if (msg.match[1].toLowerCase() === 'статус') {
      return this.handleStatus(msg);
    }
    userId = msg.from.id;
    stats = (base = this.stats)[userId] != null ? base[userId] : base[userId] = newStats(userId);
    if (msg.match[1].toLowerCase() === 'тян' && stats.tyan) {
      return this.report(msg, stats, 0);
    } else {
      if ((ref = msg.match[1].toLowerCase()) === 'спок' || ref === 'будда') {
        stats.moments = [];
      } else {
        now = Date.now();
        addMoment(stats, now);
      }
      bhLevel = calculateBhLevel(stats.moments, now);
      this.report(msg, stats, bhLevel);
      return misc.saveJson('bh_stats', this.stats);
    }
  },
  report: function(msg, stats, bh) {
    var icon, ref, text;
    ref = bhToString(bh), icon = ref.icon, text = ref.text;
    return msg.reply("Ваш статус: " + stats.status + "\nУровень бугурта: " + icon + " - " + text);
  },
  handleAdmin: function(msg) {
    var base, id, params, ref, st, tyan;
    if (!this.isSudo(msg)) {
      return;
    }
    params = msg.match[2].substr(1);
    ref = params.split(' '), id = ref[0], st = ref[1], tyan = ref[2];
    if ((base = this.stats)[id] == null) {
      base[id] = newStats(Number(id));
    }
    if (st != null) {
      this.stats[id].status = st;
    }
    if (tyan != null) {
      this.stats[id].tyan = tyan === '1';
    }
    msg.reply("Статус " + id + " обновлён.");
    return misc.saveJson('bh_stats', this.stats);
  },
  handleStatus: function(msg) {
    var base, bhLevel, stats, userId;
    userId = msg.from.id;
    stats = (base = this.stats)[userId] != null ? base[userId] : base[userId] = newStats(userId);
    if ((msg.match[2] != null) && msg.match[2].startsWith(' ')) {
      stats.status = msg.match[2].substr(1);
      msg.reply('Ваш статус обновлён.');
      return misc.saveJson('bh_stats', this.stats);
    } else {
      bhLevel = calculateBhLevel(stats.moments, Date.now());
      return this.report(msg, stats, bhLevel);
    }
  }
};
