// Generated by CoffeeScript 1.10.0
var misc;

misc = require('../lib/misc');

module.exports = {
  pattern: /!dogify (.+)/,
  name: 'Dogify',
  onMsg: function(msg, safe) {
    var i, index, len, phrase, phrases;
    phrases = msg.match[1].trim().split(',');
    for (index = i = 0, len = phrases.length; i < len; index = ++i) {
      phrase = phrases[index];
      phrases[index] = encodeURIComponent(phrase.trim());
    }
    return this.sendImageFromUrl(msg, 'http://dogr.io/' + phrases.join('/') + '.png?split=false&.png');
  }
};
