// Generated by CoffeeScript 1.10.0
var misc,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

misc = require('../lib/misc');

module.exports = {
  name: 'Echo',
  pattern: /!(echo|скажи|ня) (.+)/,
  onMsg: function(msg) {
    var i, nya, parseMode, ref, txt;
    txt = msg.match[2].trim();
    if (msg.match[1] === 'ня') {
      nya = misc.randomChoice(['ня', 'ня', 'ня', 'ня', 'ня', 'ня', 'ня', 'десу', 'Карл']);
      txt = txt.replace(/([\!\?\.\,])/g, " " + nya + "$1");
      if (!/([\!\?\.\,])$/.test(txt)) {
        txt = txt + (" " + nya + "!");
      }
    }
    i = 0;
    while (i < txt.length) {
      if (ref = txt.charAt(i), indexOf.call('_*`[', ref) < 0) {
        break;
      }
      i += 1;
    }
    if (i < txt.length) {
      txt = txt.substr(0, i) + txt.charAt(i).toUpperCase() + txt.substr(i + 1);
    }
    if (/\<\w+\>.*\<\/\w+\>/.test(txt)) {
      parseMode = 'HTML';
    } else {
      parseMode = 'Markdown';
    }
    if (/н[я]+$/i.test(txt)) {
      txt += " ❤";
    }
    return msg.send(txt, {
      parseMode: parseMode
    });
  }
};
