// Generated by CoffeeScript 1.9.1
module.exports = {
  name: 'Echo',
  pattern: /!(echo|скажи) (.+)/,
  onMsg: function(msg) {
    var txt;
    txt = msg.match[2].trim();
    if (!txt.startsWith('/') && !txt.startsWith('!')) {
      txt = txt.charAt(0).toUpperCase() + txt.substr(1);
      if (/н[я]+$/i.test(txt)) {
        txt += " ❤";
      }
      return msg.send(txt);
    }
  }
};
