// Generated by CoffeeScript 1.9.1
var misc;

misc = require('../lib/misc');

module.exports = {
  name: 'Google',
  pattern: /!(поиск|ищи|найди|гугл|g|поищи|найти|gg) ([^]+)/,
  onMsg: function(msg, safe) {
    var cmd, txt;
    cmd = msg.match[1];
    txt = msg.match[2];
    return safe(misc.google(txt)).then(function(results) {
      var answer, result, url;
      if (results.length === 0) {
        return msg.reply('Ничего не найдено!');
      } else {
        result = results[0];
        url = result.unescapedUrl;
        if (cmd === 'gg') {
          answer = result.titleNoFormatting + "\n" + url;
        } else {
          answer = url;
        }
        return msg.send(answer);
      }
    });
  },
  onError: function(msg) {
    return msg.send('Поиск не удался...');
  }
};
