// Generated by CoffeeScript 1.10.0
var misc;

misc = require('../lib/misc');

module.exports = {
  name: 'Google',
  pattern: /!(поиск|ищи|найди|гугл|g|поищи|найти|gg)(?: ([^]+))?/,
  onMsg: function(msg, safe) {
    var cmd, ref, reply_to_id, txt;
    cmd = msg.match[1];
    txt = msg.match[2];
    reply_to_id = msg.message_id;
    if ((txt == null) && (((ref = msg.reply_to_message) != null ? ref.text : void 0) != null)) {
      txt = msg.reply_to_message.text;
      reply_to_id = msg.reply_to_message.message_id;
    }
    if (txt == null) {
      return;
    }
    return safe(misc.google(txt)).then(function(results) {
      var answer, result, url;
      if (results.length === 0) {
        return msg.send('Ничего не найдено!', {
          reply: reply_to_id
        });
      } else {
        result = results[0];
        url = result.unescapedUrl;
        if (cmd === 'gg') {
          answer = result.titleNoFormatting + "\n" + url;
        } else {
          answer = url;
        }
        return msg.send(answer, {
          reply: reply_to_id
        });
      }
    });
  },
  onError: function(msg) {
    return msg.send('Поиск не удался...');
  }
};
