// Generated by CoffeeScript 1.10.0
var config, keys, logger, misc, search;

logger = require('winston');

config = require('../lib/config');

misc = require('../lib/misc');

keys = {};

search = function(txt, rsz) {
  if (rsz == null) {
    rsz = 1;
  }
  return misc.get("https://www.googleapis.com/customsearch/v1?", {
    qs: {
      key: config.options.googlekey,
      cx: config.options.googlecx,
      gl: 'ru',
      hl: 'ru',
      num: rsz,
      safe: 'high',
      searchType: 'image',
      q: txt
    },
    json: true
  }).then(function(res) {
    return res.items;
  });
};

module.exports = {
  name: 'Images',
  pattern: /!(покажи|пик|кек|пек|img|pic|moar|моар|more|еще|ещё)(?: (.+))?/,
  isConf: true,
  onMsg: function(msg, safe) {
    var key, ref, ref1, res, txt;
    txt = msg.match[2];
    if ((txt == null) && (((ref = msg.reply_to_message) != null ? ref.text : void 0) != null)) {
      txt = msg.reply_to_message.text;
    }
    if ((txt == null) && ((ref1 = msg.match[1].toLowerCase()) === 'moar' || ref1 === 'моар' || ref1 === 'more' || ref1 === 'еще' || ref1 === 'ещё')) {
      txt = this.lastText;
    }
    if (txt == null) {
      return;
    }
    this.lastText = txt;
    key = txt + "$$" + msg.chat.id;
    if (!(key in keys)) {
      keys[key] = true;
      res = search(txt);
    } else {
      logger.info("Repeated: " + key);
      res = search(txt, 8);
    }
    return safe(res).then((function(_this) {
      return function(results) {
        var result, url;
        if ((results == null) || results.length === 0) {
          return msg.reply("Ничего не найдено!");
        } else {
          result = misc.randomChoice(results);
          url = result.link;
          return _this.sendImageFromUrl(msg, url, {
            reply: msg.id
          });
        }
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send('Поиск не удался...');
  }
};
