// Generated by CoffeeScript 1.9.1
module.exports = {
  name: 'InviteMe',
  pattern: /!inv (\d+)$/,
  isPrivileged: true,
  onMsg: function(msg) {
    var id;
    return id = parseInt(msg.match[1], 10);
  }
};
