// Generated by CoffeeScript 1.10.0
var Xor4k, iq, misc, msgCache;

misc = require('../lib/misc');

msgCache = require('../lib/msg_cache');

Xor4k = require('../lib/xor4096');

iq = function(s) {
  var res, xorgen;
  xorgen = new Xor4k(s + 'sas' + new Date().toDateString());
  res = xorgen.double();
  if (res < 0.5) {
    return 30 + Math.round(res * 100);
  } else {
    return 80 + Math.round(res * 100);
  }
};

module.exports = {
  pattern: /\/iq/,
  name: 'IQ Test',
  onMsg: function(msg) {
    return msg.reply("Ваш IQ: " + (iq(misc.fullName(msg.from))));
  }
};
