// Generated by CoffeeScript 1.10.0
(function() {
  var eat, keyboard, weather;

  weather = require('./weather');

  eat = require('./eat');

  keyboard = [
    [
      {
        text: 'Погода',
        callback_data: 'weather'
      }, {
        text: 'Еда',
        callback_data: 'eat'
      }
    ]
  ];

  module.exports = {
    name: 'Location plugins',
    isConf: false,
    isAcceptMsg: function(msg) {
      return msg.location != null;
    },
    onMsg: function(msg, safe) {
      return msg.send('Выберите действие.', {
        inlineKeyboard: keyboard,
        callback: (function(_this) {
          return function(_cb, _msg) {
            return _this.onCallback(_cb, _msg, msg, safe);
          };
        })(this)
      });
    },
    onCallback: function(cb, msg, location_msg, safe) {
      if (cb.data != null) {
        if (cb.data === 'weather') {
          return weather.onLocation(msg, location_msg, safe);
        } else if (cb.data === 'eat') {
          return eat.onLocation(msg, location_msg, safe);
        }
      }
    }
  };

}).call(this);
