// Generated by CoffeeScript 1.9.1
var query;

query = require('../lib/query');

module.exports = {
  name: 'Debug',
  pattern: /!(getme|import-names|nokey)$/,
  isPrivileged: true,
  onMsg: function(msg) {
    var quotes;
    if (msg.match[1] === 'getme') {
      return query('getMe').then(function(json) {
        return logger.info(JSON.stringify(json));
      });
    } else if (msg.match[1] === 'import-names') {
      quotes = require('../lib/quotes');
      quotes.init();
      return quotes.importSavedNames();
    } else if (msg.match[1] === 'nokey') {
      return msg.send('Убираю клавиатуру', {
        replyKeyboard: {
          hide_keyboard: true
        }
      });
    } else {
      return logger.info("Unknown debug: " + msg.match[1]);
    }
  }
};
