// Generated by CoffeeScript 1.10.0
var query, tg,
  slice = [].slice;

query = require('../lib/query');

tg = require('../lib/tg');

module.exports = {
  name: 'Debug',
  pattern: /!(getme|import-names|qname|nokey|leave)(?:\s+(.+))?$/,
  isPrivileged: true,
  onMsg: function(msg) {
    var id, name, quotes, ref;
    if (msg.match[1] === 'getme') {
      return query('getMe').then(function(json) {
        return logger.info(JSON.stringify(json));
      });
    } else if (msg.match[1] === 'import-names') {
      quotes = require('../lib/quotes');
      quotes.init();
      return quotes.importSavedNames();
    } else if (msg.match[1] === 'qname') {
      ref = msg.match[2].split(' '), id = ref[0], name = 2 <= ref.length ? slice.call(ref, 1) : [];
      id = Number(id);
      name = name.join(' ');
      quotes = require('../lib/quotes');
      quotes.init();
      quotes.setSavedName(id, name);
      return msg.reply("Set saved name for " + id + ": " + name);
    } else if (msg.match[1] === 'nokey') {
      return msg.send('Ставлю клавиатуру', {
        replyKeyboard: {
          keyboard: [['1']]
        }
      }).then(function() {
        return msg.send('Убираю клавиатуру', {
          replyKeyboard: {
            hide_keyboard: true
          }
        });
      });
    } else if (msg.match[1] === 'leave') {
      return tg.leaveChat({
        chat_id: msg.match[2]
      });
    } else {
      return logger.info("Unknown debug: " + msg.match[1]);
    }
  }
};
