// Generated by CoffeeScript 1.10.0
var config, formatDate, misc, oil, pq, search;

misc = require('../lib/misc');

config = require('../lib/config');

pq = require('../lib/promise');

search = function() {
  return misc.get("https://openexchangerates.org/api/latest.json", {
    qs: {
      app_id: config.options.exchangekey
    },
    json: true
  });
};

oil = function() {
  return misc.get("http://www.forexpf.ru/_informer_/commodities.php").then(function(first) {
    var id;
    id = /comod\.php\?id=(\d+)/.exec(first)[1];
    return misc.get("http://www.forexpf.ru/_informer_/comod.php?id=" + id);
  }).then(function(second) {
    var cbrenta, cbrentb;
    cbrenta = Number(/document\.getElementById\(\"cbrenta\"\)\.innerHTML=\"([\d\.]+)\"/.exec(second)[1]);
    cbrentb = Number(/document\.getElementById\(\"cbrentb\"\)\.innerHTML=\"([\d\.]+)\"/.exec(second)[1]);
    return (cbrenta + cbrentb) / 2;
  });
};

formatDate = function(date) {
  var d, m, y;
  d = date.getDate();
  if (d < 10) {
    d = "0" + d;
  }
  m = date.getMonth() + 1;
  if (m < 10) {
    m = "0" + m;
  }
  y = date.getFullYear();
  return (d + "." + m + "." + y + " ") + date.toLocaleTimeString();
};

module.exports = {
  name: 'Currency',
  pattern: /!курс(?:\s+(.+))?/,
  isConf: true,
  onMsg: function(msg, safe) {
    return safe(pq.all([search(), oil()])).then(function(arg) {
      var calc, date, json, oil, txt;
      json = arg[0], oil = arg[1];
      date = new Date(json.timestamp * 1000);
      calc = function(from, to) {
        var f, t;
        f = json.rates[from];
        t = json.rates[to];
        return (t / f).toFixed(2);
      };
      txt = "Курс на " + (formatDate(date)) + "\n\n1 Brent = " + (oil.toFixed(2)) + " $\n1 $ = " + (calc('USD', 'RUB')) + " деревяшек\n1 Euro = " + (calc('EUR', 'RUB')) + " деревяшек\n1 CHF = " + (calc('CHF', 'RUB')) + " деревяшек\n1 Bitcoin = " + (calc('BTC', 'RUB')) + " деревяшек\n1 гривна = " + (calc('UAH', 'RUB')) + " деревяшек\n1 деревяшка = " + (calc('RUB', 'BYR')) + " перков";
      return msg.send(txt);
    });
  },
  onError: function(msg) {
    return msg.send('65 копеек, как у дедов!');
  }
};
