// Generated by CoffeeScript 1.10.0
var getPage, iconv, misc;

iconv = require('iconv-lite');

misc = require('../lib/misc');

getPage = function(url) {
  return misc.get(url, {
    encoding: null
  }).then(function(buf) {
    return iconv.decode(buf, 'win1251');
  });
};

module.exports = {
  name: 'nya.sh',
  pattern: /!(няш|мяш|няшмяш)\b/,
  onMsg: function(msg, safe) {
    var num;
    if (msg.match[1].toLowerCase() === 'няшмяш') {
      return this.trigger(msg, '!покажи няшмяш');
    } else if (msg.match[1].toLowerCase() === 'мяш') {
      num = misc.random(3404) + 1;
      return this.sendPic(msg, safe, num);
    } else {
      num = misc.random(8087) + 1;
      return this.sendPost(msg, safe, num);
    }
  },
  sendPic: function(msg, safe, num) {
    return safe(getPage("http://nya.sh/pic/" + num)).then((function(_this) {
      return function(page) {
        var url;
        url = "http://nya.sh" + page.match(/<img src="([^"]+?)" alt="pic" class="irl" \/>/)[1];
        return _this.sendImageFromUrl(msg, url, {
          caption: "http://nya.sh/pic/" + num
        });
      };
    })(this));
  },
  sendPost: function(msg, safe, num) {
    return safe(getPage("http://nya.sh/post/" + num)).then((function(_this) {
      return function(page) {
        var text;
        text = page.match(/<div class="content">([^]+?)<\/div>/)[1].replace(/<br \/>/g, '');
        text = misc.entities.decode(text);
        text = ("Цитата №" + num + "\n\n") + text;
        return msg.send(text);
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send("Ошибка! Ньоро~н...");
  }
};
