// Generated by CoffeeScript 1.9.1
var misc, msgCache, pq, quotes;

pq = require('../lib/promise');

quotes = require('../lib/quotes');

msgCache = require('../lib/msg_cache');

misc = require('../lib/misc');

module.exports = {
  name: 'Quotes (get)',
  pattern: /!(q|цитата|quote|удали|stats)(?:\s+(.+))?$/,
  init: function() {
    return quotes.init();
  },
  onMsg: function(msg) {
    var hdr, num, ownerId, quote, rating, ratingStr, reply, savedName, txt;
    if (msg.match[1].toLowerCase() === 'удали') {
      if (!this.checkSudo(msg)) {
        return;
      }
      num = misc.tryParseInt(msg.match[2]);
      if (num == null) {
        return;
      }
      quote = quotes.getByNumber(num);
      if (quote == null) {
        msg.reply("Цитата с номером " + num + " не найдена.");
        return;
      }
      if (quote.posterId !== msg.from.id && !this.bot.isSudo(msg)) {
        msg.reply("Нельзя удалять чужие цитаты.");
        return;
      }
      quotes.delQuote(num);
      msg.reply("Цитата " + num + " удалена.");
      return;
    }
    if (msg.match[1].toLowerCase() === 'stats') {
      msg.send(quotes.getStats(msg.match[2]));
      return;
    }
    quotes.updateUsers();
    if (msg.reply_to_message != null) {
      reply = msg.reply_to_message;
      if (reply.forward_from != null) {
        ownerId = reply.forward_from.id;
      } else {
        ownerId = reply.from.id;
      }
    } else {
      ownerId = null;
    }
    if (msg.match[2] != null) {
      txt = msg.match[2].trim();
      num = null;
      if (txt.endsWith('+')) {
        num = misc.tryParseInt(txt.substr(0, txt.length - 1));
        if (num != null) {
          quote = quotes.getByNumberPlus(num);
        }
      }
      if (num == null) {
        num = misc.tryParseInt(txt);
        if (num != null) {
          quote = quotes.getByNumber(num);
        } else {
          quote = quotes.getByText(msg.match[2].trim(), ownerId);
        }
      }
    } else {
      if (ownerId != null) {
        quote = quotes.getByOwnerId(ownerId);
      } else {
        quote = quotes.getRandom();
      }
    }
    if (quote != null) {
      hdr = "Цитата №" + quote.num;
      if (quote.version <= 2) {
        savedName = quote.saved_name;
      } else {
        savedName = quote.messages.map(function(mm) {
          return mm.saved_name;
        }).filter(function(n) {
          return n != null;
        }).join(", ");
      }
      if ((savedName != null) && savedName !== "") {
        hdr += " (" + savedName + ")";
      }
      if (quote.version < 5) {
        hdr += " (архив)";
      }
      rating = quotes.getRating(quote.num);
      if (rating > 0) {
        ratingStr = "+" + rating;
      } else {
        ratingStr = "" + rating;
      }
      hdr += " [ " + ratingStr + " ]";
      hdr += " " + quotes.THUMBS_UP + " /palec_VEPH_" + quote.num + " " + quotes.THUMBS_DOWN + " /palec_HU3_" + quote.num;
      quotes.setLastQuote(msg.chat.id, quote.num);
      return msg.send(hdr).then((function(_this) {
        return function() {
          var buf, fwdFunc;
          if (quote.version >= 5) {
            fwdFunc = function(msgIndex) {
              if (msgIndex < quote.messages.length) {
                return msg.forward(quote.messages[msgIndex].id, quote.messages[msgIndex].chat_id).then(function() {
                  return fwdFunc(msgIndex + 1);
                });
              }
            };
            return fwdFunc(0);
          } else {
            if (quote.version >= 3) {
              fwdFunc = function(msgIndex) {
                var buf, message;
                if (msgIndex < quote.messages.length) {
                  message = quote.messages[msgIndex];
                  buf = "<" + (message.sender_name.replace('_', ' ')) + ">\n\n";
                  if (message.text != null) {
                    buf += message.text;
                    return msg.send(buf).then(function() {
                      return fwdFunc(msgIndex + 1);
                    });
                  } else {
                    return fwdFunc(msgIndex + 1);
                  }
                }
              };
              return fwdFunc(0);
            } else {
              buf = "<" + (quote.sender_name.replace('_', ' ')) + ">\n\n";
              if (quote.reply_text != null) {
                buf += '> ' + quote.reply_text.replace(/\n/g, '\n> ') + "\n";
              }
              buf += quote.text;
              return msg.send(buf);
            }
          }
        };
      })(this));
    } else {
      return msg.reply('Цитата не найдена :(');
    }
  }
};
