// Generated by CoffeeScript 1.9.1
var config, logger, misc, quotes, tg;

logger = require('winston');

quotes = require('../lib/quotes');

misc = require('../lib/misc');

config = require('../lib/config');

tg = require('../lib/tg');

module.exports = {
  name: 'Quotes (vote)',
  pattern: /\/(LOYS|FUUU|ЛОЙС|ФУУУ|лайк|дизлайк|like|dislike|palec_VEPH|palec_HU3)(?:(?:_|\s+)(\d+))?/,
  init: function() {
    return quotes.init();
  },
  onMsg: function(msg) {
    var isThumbsUp, num, rating, ref;
    isThumbsUp = (ref = msg.match[1].toLowerCase()) === "loys" || ref === "лойс" || ref === "лайк" || ref === "like" || ref === "palec_veph";
    num = misc.tryParseInt(msg.match[2]);
    num = quotes.vote(num, msg.chat.id, msg.from.id, isThumbsUp);
    if (num != null) {
      rating = quotes.getRating(num);
      if (rating > 0) {
        rating = "+" + rating;
      }
      return tg.sendMessage({
        chat_id: msg.from.id,
        text: "Ваш голос " + (isThumbsUp ? quotes.THUMBS_UP : quotes.THUMBS_DOWN) + " учтён. Рейтинг цитаты №" + num + ": [ " + rating + " ]"
      });
    }
  }
};
