// Generated by CoffeeScript 1.12.6
var config, msgCache, quotes,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

config = require('../lib/config');

quotes = require('../lib/quotes');

msgCache = require('../lib/msg_cache');

module.exports = {
  name: 'Quotes (save)',
  pattern: /!?(запомни|сохрани|запиши|save)$/,
  isAcceptFwd: true,
  isPrivileged: true,
  warnPrivileged: false,
  init: function() {
    quotes.init();
    this.timers = {};
    return this.sudoList = config.toIdList(config.options.quotes_sudo);
  },
  isAcceptMsg: function(msg) {
    return (msg.forward_from != null) && msg.chat.type === 'private' || (msg.forward_from == null) && (msg.reply_to_message != null) && this.matchPattern(msg, msg.text);
  },
  onMsg: function(msg) {
    var msgAuthorId, num, posterId, quoteMsg;
    quotes.updateUsers();
    if (msg.forward_from != null) {
      quoteMsg = msg;
    } else {
      quoteMsg = msgCache.tryResolve(msg.reply_to_message);
    }
    if (quoteMsg.forward_from != null) {
      msgAuthorId = quoteMsg.forward_from.id;
    } else {
      msgAuthorId = quoteMsg.from.id;
    }
    if (msgAuthorId === msg.from.id && !this.bot.isSudo(msg)) {
      msg.reply("Сам себя не похвалишь - никто не похвалит, да?");
      return;
    }
    posterId = msg.from.id;
    num = quotes.add(quoteMsg, posterId);
    if (this.timers[posterId] != null) {
      clearTimeout(this.timers[posterId]);
    }
    return this.timers[posterId] = setTimeout((function(_this) {
      return function() {
        msg.send("Запомнила под номером " + num + ".", {
          reply: quoteMsg.message_id
        });
        return _this.timers[posterId] = null;
      };
    })(this), quotes.QUOTE_MERGE_TIMEOUT);
  },
  isSudo: function(msg) {
    var ref;
    return this.bot.isSudo(msg) || (ref = msg.from.id, indexOf.call(this.sudoList, ref) >= 0);
  }
};
