// Generated by CoffeeScript 1.9.1
module.exports = {
  pattern: /!тихо$/,
  name: 'Silence',
  isPrivileged: true,
  onMsg: function(msg) {
    return this.bot.setQuietMode(Date.now() + 300000);
  }
};
