// Generated by CoffeeScript 1.12.6
var config,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

config = require('../lib/config');

module.exports = {
  pattern: /!!?тихо$/,
  name: 'Silence',
  isPrivileged: true,
  init: function() {
    return this.sudoList = config.toIdList(config.options.quotes_sudo);
  },
  onMsg: function(msg) {
    var dur;
    if (msg.text === '!!тихо') {
      dur = 1800000;
    } else {
      dur = 300000;
    }
    return this.bot.setQuietMode(Date.now() + dur);
  },
  isSudo: function(msg) {
    var ref;
    return this.bot.isSudo(msg) || (ref = msg.from.id, indexOf.call(this.sudoList, ref) >= 0);
  }
};
