// Generated by CoffeeScript 1.12.6
var logger, misc, translate;

logger = require('winston');

misc = require('../lib/misc');

translate = function(src, dest, txt) {
  return misc.getAsBrowser("http://translate.google.com/translate_a/single", {
    qs: {
      client: 's',
      ie: 'UTF-8',
      oe: 'UTF-8',
      dt: 't',
      sl: src,
      tl: dest,
      q: txt
    }
  }).then(function(res) {
    var d, evalFn, ex, json;
    try {
      evalFn = new Function("return " + res);
      json = evalFn();
      return ((function() {
        var i, len, ref, results;
        ref = json[0];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          d = ref[i];
          results.push(d[0]);
        }
        return results;
      })()).join("");
    } catch (error) {
      ex = error;
      logger.debug(res);
      return null;
    }
  });
};

module.exports = {
  name: 'Translate',
  pattern: /!(переведи|translate|перевод|расшифруй|tr)( [a-z]{2})?( [a-z]{2})?(?: ([^]+))?$/,
  onMsg: function(msg, safe) {
    var dest, ref, ref1, ref2, src, text;
    if ((msg.match[2] != null) && (msg.match[3] == null)) {
      src = 'auto';
      dest = msg.match[2].trim();
    } else {
      src = ((ref = msg.match[2]) != null ? ref : 'auto').trim();
      dest = ((ref1 = msg.match[3]) != null ? ref1 : 'ru').trim();
    }
    if (src === 'auto' && msg.match[1].toLowerCase() === 'расшифруй') {
      src = 'ja';
    }
    if (msg.match[4] != null) {
      text = msg.match[4].trim();
    } else if (((ref2 = msg.reply_to_message) != null ? ref2.text : void 0) != null) {
      text = msg.reply_to_message.text;
    } else {
      return;
    }
    return safe(translate(src, dest, text)).then(function(res) {
      if (res != null) {
        return msg.reply("Перевод: " + res);
      } else {
        return msg.send("Сервис недоступен.");
      }
    });
  },
  onError: function(msg) {
    return msg.send('Не понимаю я эти ваши иероглифы.');
  }
};
