// Generated by CoffeeScript 1.10.0
var misc;

misc = require('../lib/misc');

module.exports = {
  name: 'VNDB',
  pattern: /!(vn|вн)(?: (.+))?$/,
  onMsg: function(msg, safe) {
    var q, qq;
    if (msg.match[2] != null) {
      q = msg.match[2];
      qq = encodeURIComponent(q);
      return safe(misc.get("https://vndb.org/v/all?o=d;s=pop;q=" + qq)).then((function(_this) {
        return function(page) {
          var mm;
          mm = page.match(/<td class="tc1"><a href="(.*?)"/);
          if (mm != null) {
            return _this.parseVnFrom(msg, safe, "https://vndb.org" + mm[1]);
          } else {
            return _this.parseVn(msg, page);
          }
        };
      })(this));
    } else {
      return this.parseVnFrom(msg, safe, "https://vndb.org/v/rand");
    }
  },
  parseVnFrom: function(msg, safe, url) {
    return safe(misc.get(url)).then((function(_this) {
      return function(page) {
        return _this.parseVn(msg, page);
      };
    })(this));
  },
  parseVn: function(msg, page) {
    var descr, img, title, url;
    title = page.match(/<title>(.+?)<\/title>/)[1];
    img = "https://s.vndb.org/" + page.match(/<img src="\/\/s\.vndb\.org\/(.+?)"/)[1];
    descr = page.match(/<h2>Description<\/h2><p>([^]+?)<\/p>/)[1].replace(/<br \/>/g, '\n').replace(/<a href="(.+?)"([^]+?)<\/a>/g, '$1');
    url = "https://vndb.org" + page.match(/<li class="tabselected"><a href="(.+?)"/)[1];
    return msg.send(title + "\n" + url + "\n\n" + descr, {
      preview: false
    }).then((function(_this) {
      return function() {
        return _this.sendImageFromUrl(msg, img, {
          caption: title
        });
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send("Китайские порноальбомы - не нужны.");
  }
};
