// Generated by CoffeeScript 1.9.1
var config;

config = require('../lib/config');

module.exports = {
  name: 'Welcome',
  pattern: /!(welcome|intro)$/,
  isAcceptMsg: function(msg) {
    return (msg.new_chat_participant != null) || this.isSudo(msg) && this.matchPattern(msg, msg.text);
  },
  onMsg: function(msg) {
    var user;
    if (msg.new_chat_participant == null) {
      if (msg.text === '!welcome') {
        return this.welcomeUser(msg, msg.from);
      } else {
        return this.intro(msg);
      }
    } else {
      user = msg.new_chat_participant;
      if (user.username === config.userName) {
        return this.intro(msg);
      } else {
        if ((user.username != null) && user.username.endsWith('bot')) {
          return;
        }
        return this.welcomeUser(msg, user);
      }
    }
  },
  intro: function(msg) {
    return msg.send("Всем привет! Я очень умная, и могу делать много разных вещей. Введите /help, чтобы посмотреть список команд.");
  },
  welcomeUser: function(msg, user) {
    return msg.send("Добро пожаловать, " + user.first_name + "!");
  }
};
