// Generated by CoffeeScript 1.10.0
var getJson, misc, pq;

misc = require('../lib/misc');

pq = require('../lib/promise');

getJson = function(url) {
  return misc.get(url, {
    json: true
  });
};

module.exports = {
  name: 'XKCD (en)',
  pattern: /!xkcd en(?: (\d+))?$/,
  onMsg: function(msg, safe) {
    var getNum, num;
    num = misc.tryParseInt(msg.match[1]);
    if (num != null) {
      getNum = pq.resolved(num);
    } else {
      getNum = getJson("http://xkcd.com/info.0.json").then(function(json) {
        return misc.random(json.num) + 1;
      });
    }
    return safe(getNum).then(function(num) {
      return safe(getJson("http://xkcd.com/" + num + "/info.0.json")).then(function(json) {
        return msg.send(json.num + ". " + json.title + "\n" + json.img).then(function(sent) {
          return msg.send(json.alt, {
            reply: sent.message_id,
            preview: false
          });
        });
      });
    });
  },
  onError: function(msg) {
    return msg.send("Комикс не найден.");
  }
};
