// Generated by CoffeeScript 1.9.1
var getNums, logger, misc, nums, pq, search,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

misc = require('../lib/misc');

pq = require('../lib/promise');

logger = require('winston');

nums = null;

getNums = function() {
  if (nums != null) {
    return pq.resolved(nums);
  } else {
    nums = [];
    logger.info("Reloading russian xkcd nums...");
    return misc.get("http://xkcd.ru/num/").then(function(page) {
      var mm, re;
      re = /<li class="real "><a href="\/(\d+)\//g;
      while ((mm = re.exec(page)) != null) {
        nums.push(Number(mm[1]));
      }
      return nums;
    });
  }
};

search = function(num) {
  return misc.get("http://xkcd.ru/" + num + "/").then(function(page) {
    return {
      title: page.match(/<h1>(.*?)<\/h1>/)[1],
      img: "http://xkcd.ru/i/" + page.match(/<img border=0 src="http:\/\/xkcd\.ru\/i\/(.+?)"/)[1],
      alt: page.match(/<div class="comics_text">([^]*?)<\/div>/)[1]
    };
  });
};

module.exports = {
  name: 'XKCD (ru)',
  pattern: /!xkcd(?: (\d+))?$/,
  onMsg: function(msg, safe) {
    return safe(getNums()).then((function(_this) {
      return function(nums) {
        var num;
        num = misc.tryParseInt(msg.match[1]);
        if (num == null) {
          num = misc.randomChoice(nums);
        } else if (indexOf.call(nums, num) < 0) {
          return _this.trigger(msg, "!xkcd en " + num);
        }
        return safe(search(num)).then(function(res) {
          return msg.send(num + ". " + res.title + "\n" + res.img).then(function(sent) {
            return msg.send(res.alt, {
              reply: sent.message_id,
              preview: false
            });
          });
        });
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send("Комикс не найден.");
  }
};
