// Generated by CoffeeScript 1.9.1
var config, keys, logger, misc, search;

logger = require('winston');

config = require('../lib/config');

misc = require('../lib/misc');

keys = {};

search = function(txt, num) {
  if (num == null) {
    num = 1;
  }
  return misc.get("https://www.googleapis.com/youtube/v3/search", {
    qs: {
      part: 'snippet',
      type: 'video',
      maxResults: num,
      key: config.options.googlekey,
      q: txt
    },
    json: true,
    silent: true
  }).then(function(json) {
    return json.items;
  });
};

module.exports = {
  name: 'YouTube',
  pattern: /!(youtube|видео|клип|video|yt|ютуб) (.+)/,
  onMsg: function(msg, safe) {
    var key, res, txt;
    txt = msg.match[2];
    key = txt + "$$" + msg.chat.id;
    if (!(key in keys)) {
      keys[key] = true;
      res = search(txt);
    } else {
      logger.info("Repeated: " + key);
      res = search(txt, 8);
    }
    return safe(res).then((function(_this) {
      return function(results) {
        var result, url;
        if (results.length === 0) {
          return msg.reply("Ничего не найдено!");
        } else {
          result = misc.randomChoice(results);
          url = "https://www.youtube.com/watch?v=" + result.id.videoId;
          return msg.send(url);
        }
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send("Посмотрите лучше Nyan Cat: https://www.youtube.com/watch?v=wZZ7oFKsKzY");
  }
};
