// Generated by CoffeeScript 1.12.6
var config, keys, logger, misc, search;

logger = require('winston');

config = require('../lib/config');

misc = require('../lib/misc');

keys = {};

search = function(txt, num) {
  if (num == null) {
    num = 1;
  }
  return misc.get("https://www.googleapis.com/youtube/v3/search", {
    qs: {
      part: 'snippet',
      type: 'video',
      maxResults: num,
      key: config.options.googlekey,
      q: txt
    },
    json: true,
    silent: true
  }).then(function(json) {
    return json.items;
  });
};

module.exports = {
  name: 'YouTube',
  pattern: /!(youtube|видео|клип|video|yt|ютуб)(?: (.+))?/,
  onMsg: function(msg, safe) {
    var key, ref, reply_to_id, res, txt;
    txt = msg.match[2];
    reply_to_id = msg.message_id;
    if ((txt == null) && (((ref = msg.reply_to_message) != null ? ref.text : void 0) != null)) {
      txt = msg.reply_to_message.text;
      reply_to_id = msg.reply_to_message.message_id;
    }
    if (txt == null) {
      return;
    }
    key = txt + "$$" + msg.chat.id;
    if (!(key in keys)) {
      keys[key] = true;
      res = search(txt);
    } else {
      logger.info("Repeated: " + key);
      res = search(txt, 8);
    }
    return safe(res).then((function(_this) {
      return function(results) {
        var result, url;
        if ((results != null ? results.length : void 0) === 0) {
          return msg.send("Ничего не найдено!", {
            reply: reply_to_id
          });
        } else {
          result = misc.randomChoice(results);
          url = "https://www.youtube.com/watch?v=" + result.id.videoId;
          return msg.send(url, {
            reply: reply_to_id
          });
        }
      };
    })(this));
  },
  onError: function(msg) {
    return msg.send("Посмотрите лучше Nyan Cat: https://www.youtube.com/watch?v=wZZ7oFKsKzY");
  }
};
