// Generated by CoffeeScript 1.12.4
var FileDb, SAVE_DELAY_MS, db, delays, logger, misc;

logger = require('winston');

misc = require('./misc');

SAVE_DELAY_MS = 10000;

db = {};

delays = {
  'last_timestamp': 300000
};

module.exports = FileDb = (function() {
  FileDb.get = function(name) {
    if (!(name in db)) {
      db[name] = new FileDb(name);
      db[name].init();
    }
    return db[name];
  };

  function FileDb(name1) {
    var ref;
    this.name = name1;
    this.saveDelay = (ref = delays[this.name]) != null ? ref : SAVE_DELAY_MS;
    this._timer = null;
    this._storage = {};
    this._initialized = false;
  }

  FileDb.prototype.init = function() {
    var ref;
    if (!this._initialized) {
      logger.debug("Initializing FileDB: " + this.name);
      this._storage = (ref = misc.loadJson(this.name)) != null ? ref : {};
      this._initialized = true;
    }
  };

  FileDb.prototype.get = function() {
    return this._storage;
  };

  FileDb.prototype.update = function(fn) {
    fn(this._storage);
    return this.save();
  };

  FileDb.prototype.save = function() {
    if (this._timer !== null) {
      return;
    }
    this._timer = setTimeout((function(_this) {
      return function() {
        logger.debug("Saving FileDB: " + _this.name);
        misc.saveJson(_this.name, _this._storage);
        return _this._timer = null;
      };
    })(this), this.saveDelay);
  };

  return FileDb;

})();
