// Generated by CoffeeScript 1.9.1
var config, logger, misc, pq, query, token;

logger = require('winston');

misc = require('./misc');

pq = require('./promise');

config = require('./config');

token = config.options.token;

module.exports = query = function(method, args, options) {
  var k, myOptions, reqOptions, v;
  if (args == null) {
    args = {};
  }
  if (options == null) {
    options = {};
  }
  reqOptions = {};
  myOptions = {};
  for (k in options) {
    v = options[k];
    if (k === 'multipart') {
      myOptions[k] = v;
    } else {
      reqOptions[k] = v;
    }
  }
  if (myOptions.multipart) {
    reqOptions.formData = args;
  } else {
    reqOptions.form = args;
  }
  reqOptions.silent = true;
  return misc.post("https://api.telegram.org/bot" + token + "/" + method, reqOptions).then(function(d) {
    var data, e;
    try {
      data = JSON.parse(d);
    } catch (_error) {
      e = _error;
      logger.error("Unexpected data: " + d);
      if (d.indexOf('502 Bad Gateway') !== -1) {
        return {
          'error': 502
        };
      } else {
        return {
          'error': 'Unexpected data'
        };
      }
    }
    if (data.ok) {
      return data.result;
    } else {
      logger.error(data.description);
      return {
        'error': data.description
      };
    }
  });
};
