// Generated by CoffeeScript 1.9.1
var logger, msgCache, query;

logger = require('winston');

msgCache = require('./msg_cache');

query = require('./query');

exports.sendMessage = function(args) {
  logger.outMsg("(" + args.chat_id + ") <<< " + args.text);
  return query('sendMessage', args);
};

exports.sendPhoto = function(args) {
  var caption, ref, ref1;
  if (args.caption != null) {
    caption = ': ' + args.caption;
  } else {
    caption = '';
  }
  logger.outMsg("(" + args.chat_id + ") <<< [" + ((ref = args.photo.options) != null ? ref.contentType : void 0) + ", " + ((ref1 = args.photo.value) != null ? ref1.length : void 0) + " bytes" + caption + "]");
  return query('sendPhoto', args, {
    multipart: true
  });
};

exports.forwardMessage = function(args) {
  logger.outMsg("(" + args.chat_id + ") <<< [Forward: " + args.message_id + "]");
  return query('forwardMessage', args).then(function(msg) {
    msgCache.add(msg);
    return msg;
  });
};

exports.sendAudio = function(args) {
  var ref;
  logger.outMsg("(" + args.chat_id + ") <<< [Audio (" + ((ref = args.audio.value) != null ? ref.length : void 0) + " bytes)]");
  return query('sendAudio', args, {
    multipart: true
  });
};

exports.getInfo = function() {
  logger.info("Getting user info...");
  return query('getMe');
};
