// Generated by CoffeeScript 1.12.6
var cities, initialized, loadCities, misc, saveCities;

misc = require('./misc');

initialized = false;

cities = {};

loadCities = function() {
  var ref;
  return cities = (ref = misc.loadJson('users_cities')) != null ? ref : {};
};

saveCities = function() {
  return misc.saveJson('users_cities', cities);
};

exports.init = function() {
  if (!initialized) {
    loadCities();
    initialized = true;
  }
};

exports.add = function(userId, cityName, lat, lon) {
  cities[userId] = {
    name: cityName,
    lat: lat,
    lon: lon
  };
  return saveCities();
};

exports.get = function(userId) {
  return cities[userId];
};
